# -*- coding: utf-8 -*-
"""MLProject.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/11MgBbaMSvjVOlpdDXndyFk1Cf89Zw2YW
"""

# Import necessary libraries

import pandas as pd
import numpy as np
import seaborn as sns
sns.set(color_codes=True)
import matplotlib
import matplotlib.pyplot as plt
import matplotlib.image as mpimg

from sklearn.preprocessing import LabelEncoder
from sklearn.model_selection import train_test_split
from sklearn.metrics import mean_squared_error
from sklearn.preprocessing import StandardScaler
from sklearn.tree import plot_tree
from imblearn.over_sampling import SMOTE


from sklearn.linear_model import LinearRegression
from sklearn.ensemble import RandomForestClassifier
from sklearn.linear_model import LogisticRegression
from sklearn.tree import DecisionTreeClassifier
from sklearn.neighbors import KNeighborsClassifier
from sklearn.svm import SVC
from sklearn.naive_bayes import GaussianNB

from sklearn.metrics import confusion_matrix, classification_report
from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score

import warnings
warnings.filterwarnings("ignore")

# Load the dataset

df = pd.read_excel('ML_3673_Cancer_Data_Set.xlsx')

"""## 1. Data Understanding and Exploration"""

# Display the first few rows of the dataset

df.head()

# Get information about the dataset

df.info()

# Data types of each column in the DataFrame
df.dtypes

# Display column names of the DataFrame
df.columns

# Get the number of rows and columns in the DataFrame
df.shape

# Count non-NA cells for each column
df.count()

for column in df.columns:
# Get the first value of the current column
    value=df[column].values[0]
# Get the data type of the first value
    type_value=type(value).__name__

    print(f"column:{column} ----> first value: {value} ----> Data Type:{type(value)}")

# Descriptive statistics

df.describe().T

"""# 2. Data Preprocessing"""

# Drop Unnecessary columns

df.drop(['Unnamed: 6', 'Unnamed: 7'], axis=1, inplace=True)
df.head()

# transfer "Survived" column as dependent variable to the end of the dataset

survived_col = df.pop("Survived")
df["Survived"] = survived_col    # Append the column to the end of the dataframe
df.shape

df.head()

# Check for duplicated values

df.duplicated().sum()

# Check for missing values

df.isnull().sum()

df.drop_duplicates(inplace=True)

#shape of df after dropping duplicated rows
df.shape

#df rows after dropping duplicated rows
df.count()

# Check for missing value after dropping duplicated rows

df.isnull().sum()

#These lines of code print the unique values present in the specified columns of the df. In essence, these lines provide a quick way to inspect the categorical features in your dataset and understand the distinct values within each. This is a crucial step in data exploration, allowing you to identify potential issues like unexpected values or inconsistent labeling before proceeding with further analysis or model building.
print(df["Class"].unique())
print(df["Sex"].unique())
print(df["Hospital"].unique())
print(df["Survived"].unique())

df["Age"].value_counts()

df['Age'].unique()

# plt.figure(figsize=(6,8))
# plt.scatter(df['Age'],df['Bed Cost(£)'])

# plt.xlabel('Age')
# plt.ylabel('Bed Cost(£)')
# plt.title('Age vs Bed Cost(£)')

# plt.grid(True)
# plt.show()

# plt.figure(figsize=(6,8))
# plt.scatter(df['Bed Cost(£)'], df['Age'], c='r')

# plt.xlabel('Bed Cost(£)')
# plt.ylabel('Age')
# plt.title('Bed Cost(£) vs Age')
# plt.grid(True)
# plt.show()

# Initialize LabelEncoder

le = LabelEncoder()
for col in ['Class', 'Hospital', 'Sex']:
    df[col] = le.fit_transform(df[col])

# Drop rows with missing values in the 'Hospital' column, modifying the DataFrame in place.

df["Hospital"].dropna(inplace=True)

df.isna().sum()

df

# Plot the relationship between 'Class' and 'Sex' with 'Age'

col_to_plot=['Class', 'Sex']

plt.figure(figsize=(8,6))

for col in col_to_plot:
    if col in ['Class', 'Sex']:
        plt.scatter(df[col], df['Age'], label=col, alpha=0.6)
    else:
        plt.scatter(df[col], df['Age'], label=col, alpha=0.6)

plt.xlabel('Class, Sex')
plt.ylabel('Age')
plt.legend(loc='best')
plt.title('Class, Sex vs Age')
plt.grid(True)
plt.show()

# Plot the relationship between 'Class', 'Sex', 'Bed Cost(£)'and 'Hospital' with 'Age'.
col_to_plot=['Class', 'Sex', 'Bed Cost(£)', 'Hospital' ]

plt.figure(figsize=(8,6))

for col in col_to_plot:
    if col in ['Class', 'Sex']:

        plt.scatter(df[col], df['Age'], label=col, alpha=0.6)
    else:
        plt.scatter(df[col], df['Age'], label=col, alpha=0.6)

plt.xlabel('Class, Sex')
plt.ylabel('Age')
plt.legend(loc='best')
plt.title('Class, Sex, Bed Cost(£), Hospital vs Age')
plt.grid(True)
plt.show()

col_to_plot=['Class', 'Sex', 'Bed Cost(£)', 'Hospital' ]

plt.figure(figsize=(8,6))

for col in col_to_plot:
    if col in ['Class', 'Sex','Bed Cost(£)', 'Hospital']:
    #if col in ['Class', 'Sex']:
        plt.scatter(df[col], df['Age'], label=col, alpha=0.6)
    else:
        plt.scatter(df[col], df['Age'], label=col, alpha=0.6)

plt.xlabel('Class, Sex')
plt.ylabel('Age')
plt.legend(loc='best')
plt.title('Class, Sex, Bed Cost(£), Hospital vs Age')
plt.grid(True)
plt.show()

# Plot the relationship between 'Bed Cost(£)'and 'Hospital' with 'Age'

col_to_plot=['Bed Cost(£)', 'Hospital' ]

plt.figure(figsize=(8,6))

for col in col_to_plot:
    if col in ['Class', 'Sex']:
    #if col in ['Class', 'Sex']:
        plt.scatter(df[col], df['Age'], label=col, alpha=0.6)
    else:
        plt.scatter(df[col], df['Age'], label=col, alpha=0.6)

plt.xlabel('Bed Cost(£), Hospital')
plt.ylabel('Age')
plt.legend(loc='best')
plt.title('Bed Cost(£), Hospital vs Age')
plt.grid(True)
plt.show()

# Plot the relationship between 'Class'and 'Bed Cost(£)' with 'Age'

col_to_plot=['Class', 'Bed Cost(£)' ]

plt.figure(figsize=(8,6))

for col in col_to_plot:
    if col in ['Class', 'Sex']:
    #if col in ['Class', 'Sex']:
        plt.scatter(df[col], df['Age'], label=col, alpha=0.6)
    else:
        plt.scatter(df[col], df['Age'], label=col, alpha=0.6)

plt.xlabel('Class, Bed Cost(£)')
plt.ylabel('Age')
plt.legend(loc='best')
plt.title('Class, Bed Cost(£) vs Age')
plt.grid(True)
plt.show()

# Plot the relationship between 'Class'and 'Hospital' with 'Age'

col_to_plot=['Class', 'Hospital' ]

plt.figure(figsize=(8,6))

for col in col_to_plot:
    if col in ['Class', 'Sex']:
    #if col in ['Class', 'Sex']:
        plt.scatter(df[col], df['Age'], label=col, alpha=0.6)
    else:
        plt.scatter(df[col], df['Age'], label=col, alpha=0.6)

plt.xlabel('Class, Hospital')
plt.ylabel('Age')
plt.legend(loc='best')
plt.title('Class, Hospital vs Age')
plt.grid(True)
plt.show()

# Plot the relationship between 'Sex'and 'Hospital' with 'Age'

col_to_plot=['Sex', 'Hospital' ]

plt.figure(figsize=(8,6))

for col in col_to_plot:
    if col in ['Class', 'Sex']:
    #if col in ['Class', 'Sex']:
        plt.scatter(df[col], df['Age'], label=col, alpha=0.6)
    else:
        plt.scatter(df[col], df['Age'], label=col, alpha=0.6)

plt.xlabel('Sex, Hospital')
plt.ylabel('Age')
plt.legend(loc='best')
plt.title('Sex, Hospital vs Age')
plt.grid(True)
plt.show()

# Plot the relationship between 'Sex'and 'Bed Cost(£)' with 'Age'

col_to_plot=['Sex', 'Bed Cost(£)' ]

plt.figure(figsize=(8,6))

for col in col_to_plot:
    if col in ['Class', 'Sex']:
    #if col in ['Class', 'Sex']:
        plt.scatter(df[col], df['Age'], label=col, alpha=0.6)
    else:
        plt.scatter(df[col], df['Age'], label=col, alpha=0.6)

plt.xlabel('Sex, Bed Cost(£)')
plt.ylabel('Age')
plt.legend(loc='best')
plt.title('Sex, Bed Cost(£) vs Age')
plt.grid(True)
plt.show()

# Plot the relationship between 'Sex'and 'Hospital' with 'Age'

col_to_plot=['Sex', 'Hospital' ]

plt.figure(figsize=(8,6))

for col in col_to_plot:
    if col in ['Class', 'Sex']:
    #if col in ['Class', 'Sex']:
        plt.scatter(df[col], df['Age'], label=col, alpha=0.6)
    else:
        plt.scatter(df[col], df['Age'], label=col, alpha=0.6)

plt.xlabel('Sex, Hospital')
plt.ylabel('Age')
plt.legend(loc='best')
plt.title('Sex, Hospital vs Age')
plt.grid(True)
plt.show()

# Fill missing 'Age' values with the median age.  This is done in place to modify the original DataFrame.

df["Age"].fillna(df["Age"].median(),inplace = True)

#to ensure no missing values remain
assert df.isnull().sum().sum() == 0, "Missing values still exist!"

df.isna().sum()

df['Age'].value_counts()

import seaborn as sns
import matplotlib.pyplot as plt

#Numerical features
for col in ['Age', 'Bed Cost(£)']:
   plt.figure(figsize=(8, 6))
   sns.histplot(df[col], kde=True)  # Histogram with Kernel Density Estimate
   plt.title(f'Distribution of {col}')
   plt.show()

plt.figure(figsize=(8, 6))
sns.boxplot(y=df[col])  # Boxplot to identify outliers
plt.title(f'Boxplot of {col}')
plt.show()

# Categorical features
for col in ['Class', 'Sex', 'Hospital']:
   plt.figure(figsize=(8, 6))
   sns.countplot(x=col, data=df)
   plt.title(f'Countplot of {col}')
   plt.show()

# # Correlation Matrix
# plt.figure(figsize=(10, 8))
# sns.heatmap(df.corr(), annot=True, cmap='coolwarm', fmt=".2f")
# plt.title('Correlation Matrix')
# plt.show()

# Correlation Matrix excluding 'Class' and 'Hospital'
df_corr = df.drop(['Class', 'Hospital'], axis=1)
plt.figure(figsize=(10, 8))
sns.heatmap(df_corr.corr(), annot=True, cmap='coolwarm', fmt=".2f")
plt.title('Correlation Matrix (excluding Class and Hospital)')
plt.show()

# Correlation calculation for Class and Survived
correlation_class = df['Class'].corr(df['Survived'])
print(f"Correlation between Class and Survived: {correlation_class}")

# Correlation calculation for Hospital and Survived
correlation_hospital = df['Hospital'].corr(df['Survived'])
print(f"Correlation between Hospital and Survived: {correlation_hospital}")

df_corr = df[['Class', 'Hospital', 'Survived']]
plt.figure(figsize=(10, 8))
sns.heatmap(df_corr.corr(), annot=True, cmap='coolwarm', fmt=".2f")
plt.title('Correlation Matrix (Class, Hospital and Survive)')
plt.show()

# The p-value represents the probability of observing the obtained results (or more extreme results) if there is no real association between the two variables being compared.

# In the provided code, chi-square tests are performed to assess the relationship between:

# A small p-value (typically less than 0.05) suggests strong evidence against the null hypothesis (no association).  In this context, a small p-value would indicate a statistically significant relationship between the variables.
# A large p-value suggests weak evidence against the null hypothesis.  A large p-value would indicate that the observed relationship could be due to chance, and there's no strong evidence of a real association.


from scipy.stats import chi2_contingency

# Chi-Square test for 'Class' and 'Survived'
contingency_class = pd.crosstab(df['Class'], df['Survived'])
chi2_class, p_class, dof_class, _ = chi2_contingency(contingency_class)
print(f"Chi-Square Test for Class: p-value = {p_class}")

# Chi-Square test for 'Hospital' and 'Survived'
contingency_hospital = pd.crosstab(df['Hospital'], df['Survived'])
chi2_hospital, p_hospital, dof_hospital, _ = chi2_contingency(contingency_hospital)
print(f"Chi-Square Test for Hospital: p-value = {p_hospital}")

# prompt: what p_value shows

The p-value represents the probability of observing the obtained results (or more extreme results) if there is no real association between the two variables being compared.

In the provided code, chi-square tests are performed to assess the relationship between:

1.  **`Class` and `Survived`**:  The `p_class` value from `chi2_contingency(contingency_class)` shows the probability of observing the relationship between patient class and survival, assuming there is no actual association between them.

2.  **`Hospital` and `Survived`**: The `p_hospital` value from `chi2_contingency(contingency_hospital)` shows the probability of observing the relationship between the hospital and survival, assuming no real association.

**Interpretation:**

*   A small p-value (typically less than 0.05) suggests strong evidence against the null hypothesis (no association).  In this context, a small p-value would indicate a statistically significant relationship between the variables.
*   A large p-value suggests weak evidence against the null hypothesis.  A large p-value would indicate that the observed relationship could be due to chance, and there's no strong evidence of a real association.

#Visualizing the Results



# Survival rate by Class
sns.barplot(x='Class', y='Survived', data=df)
plt.title("Survival Rate by Class")
plt.show()

# Survival rate by Hospital
sns.barplot(x='Hospital', y='Survived', data=df)
plt.title("Survival Rate by Hospital")
plt.show()

# Calculate the normalized value counts of the 'Survived' column.

value_survived = df["Survived"].value_counts(normalize=True)

value_survived

# Survived Distributuion

plt.figure(figsize=(8,6))
sns.countplot(x="Survived",data=df)
plt.title("Survived Distributuion vs Count ")
plt.show()

df

# Initialize and fit StandardScaler to 'Age' and 'Bed Cost(£)' columns, then transform these columns.

scaler = StandardScaler()
df[["Age","Bed Cost(£)"]] = scaler.fit_transform(df[["Age","Bed Cost(£)"]])

df

"""## 3. Splitting Data into Training and Testing Sets"""

# Separate features (X) and target variable (y)

X = df.drop("Survived", axis = 1)
y = df["Survived"]

# Split the dataset to train and test set

X_train,X_test,y_train,y_test = train_test_split(X,y, test_size = 0.2, random_state = 42)

y_train.value_counts()

X_train.shape

X_test.shape

y_train.shape

y_test.shape

"""# 4. Balance class distribution"""

# Initialize SMOTE for oversampling the minority class in the training data.
# random_state ensures consistent results across multiple runs.

SMOTE_m = SMOTE(random_state = 42)

# Apply SMOTE to resample the minority class in the training data, ensuring balanced class distribution.

X_res, y_res = SMOTE_m.fit_resample(X_train,y_train)

y_res.value_counts()

import seaborn as sns
import matplotlib.pyplot as plt

# Assuming X_res and y_res are your features and target after SMOTE
# Create a DataFrame for plotting
smote_df = pd.DataFrame(X_res, columns=X.columns)
smote_df['Survived'] = y_res

# Create the countplot
plt.figure(figsize=(8, 6))
sns.countplot(x='Survived', data=smote_df)
plt.title('Survived Distribution after using SMOTE method')
plt.show()

"""# 5. Model Building and Evaluation"""

# Logistic Regression
logreg = LogisticRegression()
logreg.fit(X_train, y_train)
logreg_pred = logreg.predict(X_test)

print("Logistic Regression Accuracy:", accuracy_score(y_test, logreg_pred))
print(classification_report(y_test, logreg_pred))
print(confusion_matrix(y_test, logreg_pred))

# Logistic Regression Confusion Matrix
cm = confusion_matrix(y_test, logreg_pred)

plt.figure(figsize=(8, 6))
sns.heatmap(cm, annot=True, fmt="d", cmap="Blues",
            xticklabels=['Predicted 0', 'Predicted 1'],
            yticklabels=['Actual 0', 'Actual 1'])
plt.title('Confusion Matrix for Logistic Regression')
plt.xlabel('Predicted')
plt.ylabel('Actual')
plt.show()

# Decision Tree
dtree = DecisionTreeClassifier()
dtree.fit(X_train, y_train)
dtree_pred = dtree.predict(X_test)

print("\nDecision Tree Accuracy:", accuracy_score(y_test, dtree_pred))
print(classification_report(y_test, dtree_pred))
print(confusion_matrix(y_test, dtree_pred))

# Decision Tree Confusion Matrix
cm_dtree = confusion_matrix(y_test, dtree_pred)

plt.figure(figsize=(8, 6))
sns.heatmap(cm_dtree, annot=True, fmt="d", cmap="Blues",
            xticklabels=['Predicted 0', 'Predicted 1'],
            yticklabels=['Actual 0', 'Actual 1'])
plt.title('Confusion Matrix for Decision Tree')
plt.xlabel('Predicted')
plt.ylabel('Actual')
plt.show()

# Random Forest
rf = RandomForestClassifier()
rf.fit(X_train, y_train)
rf_pred = rf.predict(X_test)

print("\nRandom Forest Accuracy:", accuracy_score(y_test, rf_pred))
print(classification_report(y_test, rf_pred))
print(confusion_matrix(y_test, rf_pred))

# Random Forest Confusion Matrix
cm_rf = confusion_matrix(y_test, rf_pred)

plt.figure(figsize=(8, 6))
sns.heatmap(cm_rf, annot=True, fmt="d", cmap="Blues",
            xticklabels=['Predicted 0', 'Predicted 1'],
            yticklabels=['Actual 0', 'Actual 1'])
plt.title('Confusion Matrix for Random Forest')
plt.xlabel('Predicted')
plt.ylabel('Actual')
plt.show()

# Support Vector Machine (SVM)
svm = SVC()
svm.fit(X_train, y_train)
svm_pred = svm.predict(X_test)

print("\nSVM Accuracy:", accuracy_score(y_test, svm_pred))
print(classification_report(y_test, svm_pred))
print(confusion_matrix(y_test, svm_pred))

# Support Vector Machine (SVM) Confusion Matrix
cm_svm = confusion_matrix(y_test, svm_pred)

plt.figure(figsize=(8, 6))
sns.heatmap(cm_svm, annot=True, fmt="d", cmap="Blues",
            xticklabels=['Predicted 0', 'Predicted 1'],
            yticklabels=['Actual 0', 'Actual 1'])
plt.title('Confusion Matrix for Support Vector Machine (SVM)')
plt.xlabel('Predicted')
plt.ylabel('Actual')
plt.show()

# K-Nearest Neighbors (KNN)
knn = KNeighborsClassifier()
knn.fit(X_train, y_train)
knn_pred = knn.predict(X_test)

print("\nKNN Accuracy:", accuracy_score(y_test, knn_pred))
print(classification_report(y_test, knn_pred))
print(confusion_matrix(y_test, knn_pred))

# K-Nearest Neighbors (KNN) Confusion Matrix
cm_knn = confusion_matrix(y_test, knn_pred)

plt.figure(figsize=(8, 6))
sns.heatmap(cm_knn, annot=True, fmt="d", cmap="Blues",
            xticklabels=['Predicted 0', 'Predicted 1'],
            yticklabels=['Actual 0', 'Actual 1'])
plt.title('Confusion Matrix for K-Nearest Neighbors (KNN)')
plt.xlabel('Predicted')
plt.ylabel('Actual')
plt.show()

# Gaussian Naive Bayes
gnb = GaussianNB()
gnb.fit(X_train, y_train)
gnb_pred = gnb.predict(X_test)

print("\nGaussian Naive Bayes Accuracy:", accuracy_score(y_test, gnb_pred))
print(classification_report(y_test, gnb_pred))
print(confusion_matrix(y_test, gnb_pred))

# Gaussian Naive Bayes Confusion Matrix
cm_gnb = confusion_matrix(y_test, gnb_pred)

plt.figure(figsize=(8, 6))
sns.heatmap(cm_gnb, annot=True, fmt="d", cmap="Blues",
            xticklabels=['Predicted 0', 'Predicted 1'],
            yticklabels=['Actual 0', 'Actual 1'],cbar=False)
plt.title('Confusion Matrix for Gaussian Naive Bayes')
plt.xlabel('Predicted')
plt.ylabel('Actual')
plt.show()

"""# 6. Model Comparison and Selection"""

# Create a DataFrame to store the classification reports
model_names = ["Logistic Regression", "Decision Tree", "Random Forest", "SVM", "KNN", "GNB"]
models = [logreg, dtree, rf, svm, knn, gnb]
reports = {}
classification_metrics = pd.DataFrame(index=model_names, columns=['Precision', 'Recall', 'F1-score', 'Accuracy'])

for name, model in zip(model_names, models):
    pred = model.predict(X_test)
    report = classification_report(y_test, pred, output_dict=True)
    classification_metrics.loc[name, 'Precision'] = report['weighted avg']['precision']
    classification_metrics.loc[name, 'Recall'] = report['weighted avg']['recall']
    classification_metrics.loc[name, 'F1-score'] = report['weighted avg']['f1-score']
    classification_metrics.loc[name, 'Accuracy'] = report['accuracy']

# Display the table of classification reports
classification_metrics

# Store classification reports in a dictionary
model_names = ["Logistic Regression", "Decision Tree", "Random Forest", "SVM", "KNN", "GNB"]
models = [logreg, dtree, rf, svm, knn, gnb]
reports = {}

for name, model in zip(model_names, models):
    pred = model.predict(X_test)
    reports[name] = classification_report(y_test, pred, output_dict=True)

# Function to extract metrics from classification reports
def get_metrics(reports):
  precision = []
  recall = []
  f1 = []
  accuracy = []

  for model_name in model_names:
    report = reports[model_name]
    precision.append(report['weighted avg']['precision'])
    recall.append(report['weighted avg']['recall'])
    f1.append(report['weighted avg']['f1-score'])
    accuracy.append(report['accuracy'])

  return precision, recall, f1, accuracy

# Extract metrics using the function
precision, recall, f1, accuracy = get_metrics(reports)

# Create the horizontal bar chart for comparison of all models
metrics_to_plot = [precision, recall, f1, accuracy]
metric_labels = ['Precision', 'Recall', 'F1-score', 'Accuracy']

x = np.arange(len(model_names))  # the label locations
width = 0.15  # the width of the bars

fig, ax = plt.subplots(figsize=(12, 6))
rects = []

for i, metric in enumerate(metrics_to_plot):
    rects.append(ax.barh(x + i * width, metric, width, label=metric_labels[i]))

# Add some text for labels, title and custom x-axis tick labels, etc.
ax.set_xlabel('Scores')
ax.set_title('Comparison of Classification Metrics Across Models')
ax.set_yticks(x + width * 2, model_names) # Center y-ticks
ax.legend(loc='upper left') # Move legend to the left


# Attach a text label above each bar in *rects*, displaying its height.
def autolabel(rects):
    for rect in rects:
        width = rect.get_width()
        ax.annotate(f'{width:.2%}', # Display as percentage
                    xy=(width, rect.get_y() + rect.get_height() / 2),
                    xytext=(3, 0),
                    textcoords="offset points",
                    ha='left', va='center')


for rect in rects:
    autolabel(rect)

fig.tight_layout()
plt.show()